version: '3'

services:
  node:
    build: ./images/node
    volumes:
      - ./mnt/node:/mnt
      - node_modules:/mnt/node_modules
    tty: true
    ports:
      - '3000:3000'
    working_dir: /mnt

volumes:
  node_modules:
